   const menuButton = document.getElementById('menu-button');
const menu = document.getElementById('menu');
const menuLinks = menu.querySelectorAll('a');


menuButton.addEventListener('click', () => {
  menu.classList.toggle('menu-open'); 
});


menuLinks.forEach(link => {
  link.addEventListener('click', () => {
    menu.classList.remove('menu-open');
  });
});


 const translations = {
        pt: {
      // Seção "Sobre Mim"
      "Sobre mim": "Sobre mim",
      "SOBRE MIM": "Sobre mim",
    "PROGRAMAÇÃO": "Programação",
    "ASSISTENTE ADMINISTRATIVO": "Assistente Administrativo",
    "MARKETING DIGITAL": "Marketing Digital",
    "ANALISTA DE DADOS": "Analista de Dados",
    "EXPERIÊNCIAS": "Experiências",
    "CAPACIDADES": "Capacidades",
    "CONTATO": "Contato",
      "Olá, me chamo Vitor Santos. Sou Assistente Administrativo, Assistente Virtual, Programador e Analista de Dados Júnior, com habilidades de programação em Python, Flask, HTML-CSS e JavaScript. Caso precise de um dos meus serviços, me mande um e-mail por contatos. Número: +5521977080240": "Olá, me chamo Vitor Santos. Sou Assistente Administrativo, Assistente Virtual, Programador e Analista de Dados Júnior, com habilidades de programação em Python, Flask, HTML-CSS e JavaScript. Caso precise de um dos meus serviços, me mande um e-mail por contatos. Número: +5521977080240",

      // Seção "Assistente Administrativo"
      "Assistente Administrativo": "Assistente Administrativo",
      "Gerenciamento de tarefas administrativas...": "Gerenciamento de tarefas administrativas...",
      "Tenho Excel nível intermediário.": "Tenho Excel nível intermediário.",
      "Matplotlib Nível Avançado": "Matplotlib Nível Avançado",
      "PowerPoint Nível Intermediário": "PowerPoint Nível Intermediário",
      "Word Nível Intermediário": "Word Nível Intermediário",

      // Seção "Programação"
      "Programação": "Programação",
      "Sou capaz de desenvolver aplicações web e de escritórios úteis usando Python.": "Sou capaz de desenvolver aplicações web e de escritórios úteis usando Python.",
      "Sou capaz de desenvolver scripts úteis para website voltados para frond-end e node para usar como servidor local.": "Sou capaz de desenvolver scripts úteis para website voltados para frond-end e node para usar como servidor local.",
      "Sou capaz de desenvolver sites úteis para web, sites estáticos e de exibição.": "Sou capaz de desenvolver sites úteis para web, sites estáticos e de exibição.",
      "Faço sites responsivos e profissionais usando bootstrap.": "Faço sites responsivos e profissionais usando bootstrap.",
      "Uso Netlify para testar sites html-ccs, bootstrap, sites com ou sem scripts do javascript, ou até mesmo para trabalho.": "Uso Netlify para testar sites html-ccs, bootstrap, sites com ou sem scripts do javascript, ou até mesmo para trabalho.",
      "Uso Heroku para testar aplicações Python-Flask, ou até mesmo para trabalho usando aplicações úteis.": "Uso Heroku para testar aplicações Python-Flask, ou até mesmo para trabalho usando aplicações úteis.",

      // Seção "Marketing Digital"
      "Marketing Digital": "Marketing Digital",
      "Campanhas digitais e otimização SEO... Google Search console, Site maps, Instagran, Facebook": "Campanhas digitais e otimização SEO... Google Search console, Site maps, Instagran, Facebook",
      "- Search Engine Optimization (SEO) - Em PT: Otimização para motores de busca": "- Search Engine Optimization (SEO) - Em PT: Otimização para motores de busca",
      "Google Analytics - Análise de tráfego de sites...": "Google Analytics - Análise de tráfego de sites...",

      // Seção "Analista de Dados"
      "Analista de dados junior": "Analista de dados junior",
      "PYTHON e FLASK para analisar dados de maneira eficiente e com perfeição, também coletar e limpar dados com precisão. usando bibliotecas que facilitam o processo em 100%": "PYTHON e FLASK para analisar dados de maneira eficiente e com perfeição, também coletar e limpar dados com precisão. usando bibliotecas que facilitam o processo em 100%",
      "Para manipular dados e usá-los em consultas complexas de dados.": "Para manipular dados e usá-los em consultas complexas de dados.",
      "Para armazenar dados de maneira simples e organizada.": "Para armazenar dados de maneira simples e organizada.",
      "Biblioteca Chart e Leaflet, para demonstração gráfica de dados.": "Biblioteca Chart e Leaflet, para demonstração gráfica de dados.",

      // Seção "Experiências"
      "Experiências": "Experiências",
      "Outlier - geração de áudio para I.A Português para Inglês": "Outlier - geração de áudio para I.A Português para Inglês",
      "Agente de viagens - Auxiliando pessoas a conseguir passaporte com planos de cursos": "Agente de viagens - Auxiliando pessoas a conseguir passaporte com planos de cursos",
      "Assistente virtual - Writer translator freelancer pessoal de um amigo americano": "Assistente virtual - Writer translator freelancer pessoal de um amigo americano",
      "Auxiliar de serviços gerais - descarregando produtos de caminhão": "Auxiliar de serviços gerais - descarregando produtos de caminhão",
      "Ajudante de pedreiro - Ajudando a encher carrinho de areia, pegar cimentos, baldes de cimentos": "Ajudante de pedreiro - Ajudando a encher carrinho de areia, pegar cimentos, baldes de cimentos",

      // Seção "Capacidades"
      "Capacidades PYTHON, FLASK, HTML-CSS, \"ANÁLISE DE DADOS REGRESSÃO LINEAR E TESTES\"": "Capacidades PYTHON, FLASK, HTML-CSS, \"ANÁLISE DE DADOS REGRESSÃO LINEAR E TESTES\"",
      "PROJETOS: PYTHON": "PROJETOS: PYTHON",
      "Agendas comuns com banco de dados.": "Agendas comuns com banco de dados.",
      "Formulários com banco de dados, com hora e despertador.": "Formulários com banco de dados, com hora e despertador.",
      "Leitor PDF com áudio.": "Leitor PDF com áudio.",
      "Script para enviar mensagens de Email com body responsivo para mais de 20.000 pessoas \"dependendo da quantia de Emails é possível até mais\".": "Script para enviar mensagens de Email com body responsivo para mais de 20.000 pessoas \"dependendo da quantia de Emails é possível até mais\".",
      "Tradutor de áudio para txt, rtf ou srt.": "Tradutor de áudio para txt, rtf ou srt.",
      "Transformador de textos em áudios speach voz humana ou robótica, ou semelhante a humana.": "Transformador de textos em áudios speach voz humana ou robótica, ou semelhante a humana.",
      "Árvore de decisão e regressão linear.": "Árvore de decisão e regressão linear.",
      "Machine Learning.": "Machine Learning.",
      "Machine Learning com estatística e probabilidade.": "Machine Learning com estatística e probabilidade.",
      "Regressão linear.": "Regressão linear.",
      "SRT para áudio em qualquer idioma.": "SRT para áudio em qualquer idioma.",
      "Cortar bordas de vídeos.": "Cortar bordas de vídeos.",
      "Transformar texto em PDF.": "Transformar texto em PDF.",
      "Transformar texto UTF-8 em texto cp1235.": "Transformar texto UTF-8 em texto cp1235.",
      "Formulários com banco de dados, com hora e despertador.": "Formulários com banco de dados, com hora e despertador.",
      "Planilhas de Despesas.": "Planilhas de Despesas.",
      "Dashboard gráficos.": "Dashboard gráficos.",
      "Dashboard semidinâmico.": "Dashboard semidinâmico.",
      "Relógios.": "Relógios.",
      "Calculadora.": "Calculadora.",
      "App semelhante ao Wordpad.": "App semelhante ao Wordpad.",
      "App de edição de vídeos.": "App de edição de vídeos.",
      "PROJETOS: FLASK": "PROJETOS: FLASK",
      "Formulários com banco de dados.": "Formulários com banco de dados.",
      "Aplicação de Chat com banco de dados, possível enviar fotos e vídeos.": "Aplicação de Chat com banco de dados, possível enviar fotos e vídeos.",
      "Aplicação escreva a sua história, foto história, salvasse com banco de dados.": "Aplicação escreva a sua história, foto história, salvasse com banco de dados.",
      "Dashboard leitor de planilhas Excel.": "Dashboard leitor de planilhas Excel.",
      "Dashboard informador de dados de planilhas excel e csv.": "Dashboard informador de dados de planilhas excel e csv.",
      "Login com banco de dados.": "Login com banco de dados.",
      "Formulário Dashboard online com Dash.": "Formulário Dashboard online com Dash.",
      "Informação de Dados.": "Informação de Dados.",
      "PROJETOS: HTML-CSS": "PROJETOS: HTML-CSS",
      "BOOTSTRAP": "BOOTSTRAP",
      "JAVASCRIPT": "JAVASCRIPT",
      "Site de curso para 25 idiomas diferentes.": "Site de curso para 25 idiomas diferentes.",
      "Lojas de roupa.": "Lojas de roupa.",
      "Loja de artigos religiosos.": "Loja de artigos religiosos.",
      "Formulário Pessoal.": "Formulário Pessoal.",
      "Site de conteúdo adulto.": "Site de conteúdo adulto.",
      "Site de jogos.": "Site de jogos.",
      "Portifólio pessoal com login e senha.": "Portifólio pessoal com login e senha.",
      "Site para Clínica.": "Site para Clínica.",
      "Site para Oficina.": "Site para Oficina.",
      "Planilha de cálculo de despesas.": "Planilha de cálculo de despesas.",
      "Relatório de dados exemplo.": "Relatório de dados exemplo.",
      "ANÁLISE DE DADOS \"REGRESSÃO LINEAR E TESTES\"": "ANÁLISE DE DADOS \"REGRESSÃO LINEAR E TESTES\"",
      "ANÁLISES FEITAS COM PYTHON, MYSQL E EXCEL": "ANÁLISES FEITAS COM PYTHON, MYSQL E EXCEL",
      "EXIBIÇÃO DE RELATÓRIOS GRÁFICOS FLASK": "EXIBIÇÃO DE RELATÓRIOS GRÁFICOS FLASK",
      ", BOOTSTRAP, JAVASCRIPT": ", BOOTSTRAP, JAVASCRIPT",
      "CONHECIMENTOS E CAPACIDADES ABAIXO": "CONHECIMENTOS E CAPACIDADES ABAIXO",
      "Experiência com Modelagem Estatística.": "Experiência com Modelagem Estatística.",
      "statsmodels e scikit-learn.": "statsmodels e scikit-learn.",
      "Gestão e Manipulação de Bancos de Dados MYSQL.": "Gestão e Manipulação de Bancos de Dados MYSQL.",
      "Realização de análise estatística básica Excel.": "Realização de análise estatística básica Excel.",
      "Criação de dashboards interativos e relatórios dinâmicos Matplotlib, Chart e Leaflet.": "Criação de dashboards interativos e relatórios dinâmicos Matplotlib, Chart e Leaflet.",

      // Seção "Contato"
      "Contato": "Contato",
      "Entre em contato comigo por email.": "Entre em contato comigo por email.",
      "Nome:": "Nome:",
      "Email:": "Email:",
      "Mensagem:": "Mensagem:",
      "Enviar mensagem": "Enviar mensagem",
      "Ou converse comigo através do WhatsApp.": "Ou converse comigo através do WhatsApp."
    },
        en: {
          "Sobre mim": "About Me",
             "SOBRE MIM": "About Me",
    "PROGRAMAÇÃO": "Programming",
    "ASSISTENTE ADMINISTRATIVO": "Administrative Assistant",
    "MARKETING DIGITAL": "Digital Marketing",
    "ANALISTA DE DADOS": "Data Analyst",
    "EXPERIÊNCIAS": "Experiences",
    "CAPACIDADES": "Skills",
    "CONTATO": "Contact",
    "Olá, me chamo Vitor Santos. Sou Assistente Administrativo, Assistente Virtual, Programador e Analista de Dados Júnior, com habilidades de programação em Python, Flask, HTML-CSS e JavaScript. Caso precise de um dos meus serviços, me mande um e-mail por contatos. Número: +5521977080240": "Hello, my name is Vitor Santos. I am an Administrative Assistant, Virtual Assistant, Junior Programmer, and Data Analyst, with programming skills in Python, Flask, HTML-CSS, and JavaScript. If you need any of my services, send me an email through contacts. Phone number: +5521977080240",

    "Assistente Administrativo": "Administrative Assistant",
    "Gerenciamento de tarefas administrativas...": "Management of administrative tasks...",
    "Tenho Excel nível intermediário.": "I have intermediate level Excel.",
    "Matplotlib Nível Avançado": "Advanced Matplotlib",
    "PowerPoint Nível Intermediário": "Intermediate PowerPoint",
    "Word Nível Intermediário": "Intermediate Word",

    "Programação": "Programming",
    "Sou capaz de desenvolver aplicações web e de escritórios úteis usando Python.": "I can develop useful web and office applications using Python.",
    "Sou capaz de desenvolver scripts úteis para website voltados para front-end e node para usar como servidor local.": "I can develop useful website scripts aimed at front-end and node for use as a local server.",
    "Sou capaz de desenvolver sites úteis para web, sites estáticos e de exibição.": "I can develop useful web sites, static and display sites.",
    "Faço sites responsivos e profissionais usando bootstrap.": "I create responsive and professional websites using bootstrap.",
    "Uso Netlify para testar sites html-ccs, bootstrap, sites com ou sem scripts do javascript, ou até mesmo para trabalho.": "I use Netlify to test html-css sites, bootstrap, sites with or without JavaScript scripts, or even for work.",
    "Uso Heroku para testar aplicações Python-Flask, ou até mesmo para trabalho usando aplicações úteis.": "I use Heroku to test Python-Flask applications, or even for work using useful applications.",

    "Marketing Digital": "Digital Marketing",
    "Campanhas digitais e otimização SEO... Google Search console, Site maps, Instagran, Facebook": "Digital campaigns and SEO optimization... Google Search console, Sitemaps, Instagram, Facebook",
    "- Search Engine Optimization (SEO) - Em PT: Otimização para motores de busca": "- Search Engine Optimization (SEO) - In PT: Optimization for search engines",
    "Google Analytics - Análise de tráfego de sites...": "Google Analytics - Website traffic analysis...",

    "Analista de dados junior": "Junior Data Analyst",
    "PYTHON e FLASK para analisar dados de maneira eficiente e com perfeição, também coletar e limpar dados com precisão. usando bibliotecas que facilitam o processo em 100%": "PYTHON and FLASK to analyze data efficiently and perfectly, also collect and clean data with precision using libraries that facilitate the process 100%",
    "Para manipular dados e usá-los em consultas complexas de dados.": "To manipulate data and use it in complex data queries.",
    "Para armazenar dados de maneira simples e organizada.": "To store data in a simple and organized way.",
    "Biblioteca Chart e Leaflet, para demonstração gráfica de dados.": "Chart and Leaflet libraries for graphical data demonstration.",

    "Experiências": "Experience",
    "Outlier - geração de áudio para I.A Português para Inglês": "Outlier - audio generation for AI from Portuguese to English",
    "Agente de viagens - Auxiliando pessoas a conseguir passaporte com planos de cursos": "Travel Agent - Helping people get passports with course plans",
    "Assistente virtual - Writer translator freelancer pessoal de um amigo americano": "Virtual Assistant - Personal freelance writer translator for an American friend",
    "Auxiliar de serviços gerais - descarregando produtos de caminhão": "General Services Assistant - unloading truck products",
    "Ajudante de pedreiro - Ajudando a encher carrinho de areia, pegar cimentos, baldes de cimentos": "Mason's Helper - Helping fill the wheelbarrow with sand, get cement, buckets of cement",

    "Capacidades PYTHON, FLASK, HTML-CSS, \"ANÁLISE DE DADOS REGRESSÃO LINEAR E TESTES\"": "Skills PYTHON, FLASK, HTML-CSS, \"DATA ANALYSIS LINEAR REGRESSION AND TESTS\"",
    "PROJETOS: PYTHON": "PROJECTS: PYTHON",
    "Agendas comuns com banco de dados.": "Common calendars with database.",
    "Formulários com banco de dados, com hora e despertador.": "Forms with database, with time and alarm.",
    "Leitor PDF com áudio.": "PDF reader with audio.",
    "Script para enviar mensagens de Email com body responsivo para mais de 20.000 pessoas \"dependendo da quantia de Emails é possível até mais\".": "Script to send emails with responsive body to over 20,000 people \"depending on the number of emails, it can be more\".",
    "Tradutor de áudio para txt, rtf ou srt.": "Audio to txt, rtf, or srt translator.",
    "Transformador de textos em áudios speach voz humana ou robótica, ou semelhante a humana.": "Text to speech audio converter with human or robotic voice, or human-like.",
    "Árvore de decisão e regressão linear.": "Decision tree and linear regression.",
    "Machine Learning.": "Machine Learning.",
    "Machine Learning com estatística e probabilidade.": "Machine Learning with statistics and probability.",
    "Regressão linear.": "Linear regression.",
    "SRT para áudio em qualquer idioma.": "SRT to audio in any language.",
    "Cortar bordas de vídeos.": "Cut video edges.",
    "Transformar texto em PDF.": "Convert text to PDF.",
    "Transformar texto UTF-8 em texto cp1235.": "Convert UTF-8 text to cp1235 text.",
    "Formulários com banco de dados, com hora e despertador.": "Forms with database, with time and alarm.",
    "Planilhas de Despesas.": "Expense Spreadsheets.",
    "Dashboard gráficos.": "Dashboard graphics.",
    "Dashboard semidinâmico.": "Semi-dynamic dashboard.",
    "Relógios.": "Clocks.",
    "Calculadora.": "Calculator.",
    "App semelhante ao Wordpad.": "App similar to Wordpad.",
    "App de edição de vídeos.": "Video editing app.",
    "PROJETOS: FLASK": "PROJECTS: FLASK",
    "Formulários com banco de dados.": "Forms with database.",
    "Aplicação de Chat com banco de dados, possível enviar fotos e vídeos.": "Chat application with database, able to send photos and videos.",
    "Aplicação escreva a sua história, foto história, salvasse com banco de dados.": "Write your story application, photo story, saved with database.",
    "Dashboard leitor de planilhas Excel.": "Excel spreadsheet reader dashboard.",
    "Dashboard informador de dados de planilhas excel e csv.": "Dashboard that provides data from Excel and CSV spreadsheets.",
    "Login com banco de dados.": "Login with database.",
    "Formulário Dashboard online com Dash.": "Online Dashboard form with Dash.",
    "Informação de Dados.": "Data Information.",
    "PROJETOS: HTML-CSS": "PROJECTS: HTML-CSS",
    "BOOTSTRAP": "BOOTSTRAP",
    "JAVASCRIPT": "JAVASCRIPT",
    "Site de curso para 25 idiomas diferentes.": "Course site for 25 different languages.",
    "Lojas de roupa.": "Clothing stores.",
    "Loja de artigos religiosos.": "Religious items store.",
    "Formulário Pessoal.": "Personal form.",
    "Site de conteúdo adulto.": "Adult content website.",
    "Site de jogos.": "Gaming website.",
    "Portifólio pessoal com login e senha.": "Personal portfolio with login and password.",
    "Site para Clínica.": "Website for Clinic.",
    "Site para Oficina.": "Website for Workshop.",
    "Planilha de cálculo de despesas.": "Expense calculation spreadsheet.",
    "Relatório de dados exemplo.": "Sample data report.",
    "ANÁLISE DE DADOS \"REGRESSÃO LINEAR E TESTES\"": "DATA ANALYSIS \"LINEAR REGRESSION AND TESTS\"",
    "ANÁLISES FEITAS COM PYTHON, MYSQL E EXCEL": "ANALYSES MADE WITH PYTHON, MYSQL, AND EXCEL",
    "EXIBIÇÃO DE RELATÓRIOS GRÁFICOS FLASK": "GRAPHICAL REPORT DISPLAY FLASK",
    ", BOOTSTRAP, JAVASCRIPT": ", BOOTSTRAP, JAVASCRIPT",
    "CONHECIMENTOS E CAPACIDADES ABAIXO": "KNOWLEDGE AND SKILLS BELOW",
    "Experiência com Modelagem Estatística.": "Experience with Statistical Modeling.",
    "statsmodels e scikit-learn.": "statsmodels and scikit-learn.",
    "Gestão e Manipulação de Bancos de Dados MYSQL.": "Management and Manipulation of MYSQL Databases.",
    "Realização de análise estatística básica Excel.": "Performing basic statistical analysis with Excel.",
    "Criação de dashboards interativos e relatórios dinâmicos Matplotlib, Chart e Leaflet.": "Creating interactive dashboards and dynamic reports with Matplotlib, Chart, and Leaflet.",

    "Contato": "Contact",
    "Entre em contato comigo por email.": "Contact me by email.",
    "Nome:": "Name:",
    "Email:": "Email:",
    "Mensagem:": "Message:",
    "Enviar mensagem": "Send message",
    "Ou converse comigo através do WhatsApp.": "Or chat with me on WhatsApp."
        },
       es: {
  // Sección "Sobre Mí"
  "Sobre mim": "Sobre mí",
           "SOBRE MIM": "Sobre Mí",
    "PROGRAMAÇÃO": "Programación",
    "ASSISTENTE ADMINISTRATIVO": "Asistente Administrativo",
    "MARKETING DIGITAL": "Marketing Digital",
    "ANALISTA DE DADOS": "Analista de Datos",
    "EXPERIÊNCIAS": "Experiencias",
    "CAPACIDADES": "Capacidades",
    "CONTATO": "Contacto",
  "Olá, me chamo Vitor Santos. Sou Assistente Administrativo, Assistente Virtual, Programador e Analista de Dados Júnior, com habilidades de programação em Python, Flask, HTML-CSS e JavaScript. Caso precise de um dos meus serviços, me mande um e-mail por contatos. Número: +5521977080240": "Hola, me llamo Vitor Santos. Soy Asistente Administrativo, Asistente Virtual, Programador y Analista de Datos Junior, con habilidades de programación en Python, Flask, HTML-CSS y JavaScript. Si necesita alguno de mis servicios, envíeme un correo electrónico a través de contactos. Número: +5521977080240",

  // Sección "Asistente Administrativo"
  "Assistente Administrativo": "Asistente Administrativo",
  "Gerenciamento de tarefas administrativas...": "Gestión de tareas administrativas...",
  "Tenho Excel nível intermediário.": "Tengo Excel nivel intermedio.",
  "Matplotlib Nível Avançado": "Matplotlib Nivel Avanzado",
  "PowerPoint Nível Intermediário": "PowerPoint Nivel Intermedio",
  "Word Nível Intermediário": "Word Nivel Intermedio",

  // Sección "Programación"
  "Programação": "Programación",
  "Sou capaz de desenvolver aplicações web e de escritórios úteis usando Python.": "Soy capaz de desarrollar aplicaciones web y de oficina útiles usando Python.",
  "Sou capaz de desenvolver scripts úteis para website voltados para frond-end e node para usar como servidor local.": "Soy capaz de desarrollar scripts útiles para sitios web orientados al front-end y node para usar como servidor local.",
  "Sou capaz de desenvolver sites úteis para web, sites estáticos e de exibição.": "Soy capaz de desarrollar sitios web útiles, sitios estáticos y de exhibición.",
  "Faço sites responsivos e profissionais usando bootstrap.": "Hago sitios responsivos y profesionales usando bootstrap.",
  "Uso Netlify para testar sites html-ccs, bootstrap, sites com ou sem scripts do javascript, ou até mesmo para trabalho.": "Uso Netlify para probar sitios html-css, bootstrap, sitios con o sin scripts de javascript, o incluso para trabajo.",
  "Uso Heroku para testar aplicações Python-Flask, ou até mesmo para trabalho usando aplicações úteis.": "Uso Heroku para probar aplicaciones Python-Flask, o incluso para trabajo usando aplicaciones útiles.",

  // Sección "Marketing Digital"
  "Marketing Digital": "Marketing Digital",
  "Campanhas digitais e otimização SEO... Google Search console, Site maps, Instagran, Facebook": "Campañas digitales y optimización SEO... Google Search Console, Site maps, Instagram, Facebook",
  "- Search Engine Optimization (SEO) - Em PT: Otimização para motores de busca": "- Search Engine Optimization (SEO) - En ES: Optimización para motores de búsqueda",
  "Google Analytics - Análise de tráfego de sites...": "Google Analytics - Análisis de tráfico de sitios...",

  // Sección "Analista de Datos"
  "Analista de dados junior": "Analista de datos junior",
  "PYTHON e FLASK para analisar dados de maneira eficiente e com perfeição, também coletar e limpar dados com precisão. usando bibliotecas que facilitam o processo em 100%": "PYTHON y FLASK para analizar datos de manera eficiente y con perfección, también recolectar y limpiar datos con precisión. Usando bibliotecas que facilitan el proceso en un 100%",
  "Para manipular dados e usá-los em consultas complexas de dados.": "Para manipular datos y usarlos en consultas complejas de datos.",
  "Para armazenar dados de maneira simples e organizada.": "Para almacenar datos de manera simple y organizada.",
  "Biblioteca Chart e Leaflet, para demonstração gráfica de dados.": "Biblioteca Chart y Leaflet, para demostración gráfica de datos.",

  // Sección "Experiencias"
  "Experiências": "Experiencias",
  "Outlier - geração de áudio para I.A Português para Inglês": "Outlier - generación de audio para I.A Portugués a Inglés",
  "Agente de viagens - Auxiliando pessoas a conseguir passaporte com planos de cursos": "Agente de viajes - Ayudando a personas a obtener pasaporte con planes de cursos",
  "Assistente virtual - Writer translator freelancer pessoal de um amigo americano": "Asistente virtual - Writer translator freelancer personal de un amigo americano",
  "Auxiliar de serviços gerais - descarregando produtos de caminhão": "Auxiliar de servicios generales - Descargando productos de camión",
  "Ajudante de pedreiro - Ajudando a encher carrinho de areia, pegar cimentos, baldes de cimentos": "Ayudante de albañil - Ayudando a llenar carretilla de arena, recoger cementos, baldes de cemento",

  // Sección "Capacidades"
  "Capacidades PYTHON, FLASK, HTML-CSS, \"ANÁLISE DE DADOS REGRESSÃO LINEAR E TESTES\"": "Capacidades PYTHON, FLASK, HTML-CSS, \"ANÁLISIS DE DATOS REGRESIÓN LINEAL Y PRUEBAS\"",
  "PROJETOS: PYTHON": "PROYECTOS: PYTHON",
  "Agendas comuns com banco de dados.": "Agendas comunes con base de datos.",
  "Formulários com banco de dados, com hora e despertador.": "Formularios con base de datos, con hora y despertador.",
  "Leitor PDF com áudio.": "Lector PDF con audio.",
  "Script para enviar mensagens de Email com body responsivo para mais de 20.000 pessoas \"dependendo da quantia de Emails é possível até mais\".": "Script para enviar mensajes de correo electrónico con body responsivo para más de 20.000 personas \"dependiendo de la cantidad de correos electrónicos es posible incluso más\".",
  "Tradutor de áudio para txt, rtf ou srt.": "Traductor de audio a txt, rtf o srt.",
  "Transformador de textos em áudios speach voz humana ou robótica, ou semelhante a humana.": "Transformador de textos en audios speach voz humana o robótica, o similar a humana.",
  "Árvore de decisão e regressão linear.": "Árbol de decisión y regresión lineal.",
  "Machine Learning.": "Machine Learning.",
  "Machine Learning com estatística e probabilidade.": "Machine Learning con estadística y probabilidad.",
  "Regressão linear.": "Regresión lineal.",
  "SRT para áudio em qualquer idioma.": "SRT para audio en cualquier idioma.",
  "Cortar bordas de vídeos.": "Cortar bordes de videos.",
  "Transformar texto em PDF.": "Transformar texto en PDF.",
  "Transformar texto UTF-8 em texto cp1235.": "Transformar texto UTF-8 en texto cp1235.",
  "Formulários com banco de dados, com hora e despertador.": "Formularios con base de datos, con hora y despertador.",
  "Planilhas de Despesas.": "Hojas de gastos.",
  "Dashboard gráficos.": "Dashboard gráficos.",
  "Dashboard semidinâmico.": "Dashboard semidinámico.",
  "Relógios.": "Relojes.",
  "Calculadora.": "Calculadora.",
  "App semelhante ao Wordpad.": "App similar al Wordpad.",
  "App de edição de vídeos.": "App de edición de videos.",
  "PROJETOS: FLASK": "PROYECTOS: FLASK",
  "Formulários com banco de dados.": "Formularios con base de datos.",
  "Aplicação de Chat com banco de dados, possível enviar fotos e vídeos.": "Aplicación de Chat con base de datos, posible enviar fotos y videos.",
  "Aplicação escreva a sua história, foto história, salvasse com banco de dados.": "Aplicación escribe tu historia, foto historia, guardar con base de datos.",
  "Dashboard leitor de planilhas Excel.": "Dashboard lector de hojas de Excel.",
  "Dashboard informador de dados de planilhas excel e csv.": "Dashboard informador de datos de hojas de Excel y csv.",
  "Login com banco de dados.": "Login con base de datos.",
  "Formulário Dashboard online com Dash.": "Formulario Dashboard online con Dash.",
  "Informação de Dados.": "Información de Datos.",
  "PROJETOS: HTML-CSS": "PROYECTOS: HTML-CSS",
  "BOOTSTRAP": "BOOTSTRAP",
  "JAVASCRIPT": "JAVASCRIPT",
  "Site de curso para 25 idiomas diferentes.": "Sitio de curso para 25 idiomas diferentes.",
  "Lojas de roupa.": "Tiendas de ropa.",
  "Loja de artigos religiosos.": "Tienda de artículos religiosos.",
  "Formulário Pessoal.": "Formulario Personal.",
  "Site de conteúdo adulto.": "Sitio de contenido adulto.",
  "Site de jogos.": "Sitio de juegos.",
  "Portifólio pessoal com login e senha.": "Portafolio personal con login y contraseña.",
  "Site para Clínica.": "Sitio para Clínica.",
  "Site para Oficina.": "Sitio para Taller.",
  "Planilha de cálculo de despesas.": "Hoja de cálculo de gastos.",
  "Relatório de dados exemplo.": "Informe de datos ejemplo.",
  "ANÁLISE DE DADOS \"REGRESSÃO LINEAR E TESTES\"": "ANÁLISIS DE DATOS \"REGRESIÓN LINEAL Y PRUEBAS\"",
  "ANÁLISES FEITAS COM PYTHON, MYSQL E EXCEL": "ANÁLISIS HECHOS CON PYTHON, MYSQL Y EXCEL",
  "EXIBIÇÃO DE RELATÓRIOS GRÁFICOS FLASK": "EXHIBICIÓN DE INFORMES GRÁFICOS FLASK",
  ", BOOTSTRAP, JAVASCRIPT": ", BOOTSTRAP, JAVASCRIPT",
  "CONHECIMENTOS E CAPACIDADES ABAIXO": "CONOCIMIENTOS Y CAPACIDADES ABAJO",
  "Experiência com Modelagem Estatística.": "Experiencia con Modelado Estadístico.",
  "statsmodels e scikit-learn.": "statsmodels y scikit-learn.",
  "Gestão e Manipulação de Bancos de Dados MYSQL.": "Gestión y Manipulación de Bases de Datos MYSQL.",
  "Realização de análise estatística básica Excel.": "Realización de análisis estadístico básico Excel.",
  "Criação de dashboards interativos e relatórios dinâmicos Matplotlib, Chart e Leaflet.": "Creación de dashboards interactivos e informes dinámicos Matplotlib, Chart y Leaflet.",

  // Sección "Contacto"
  "Contato": "Contacto",
  "Entre em contato comigo por email.": "Contácteme por correo electrónico.",
  "Nome:": "Nombre:",
  "Email:": "Correo electrónico:",
  "Mensagem:": "Mensaje:",
  "Enviar mensagem": "Enviar mensaje",
  "Ou converse comigo através do WhatsApp.": "O converse conmigo a través de WhatsApp."
},
        fr: {
  // Section "À propos de moi"
  "Sobre mim": "À propos de moi",
        "SOBRE MIM": "À Propos de Moi",
    "PROGRAMAÇÃO": "Programmation",
    "ASSISTENTE ADMINISTRATIVO": "Assistant Administratif",
    "MARKETING DIGITAL": "Marketing Numérique",
    "ANALISTA DE DADOS": "Analyste de Données",
    "EXPERIÊNCIAS": "Expériences",
    "CAPACIDADES": "Capacités",
    "CONTATO": "Contact",
  "Olá, me chamo Vitor Santos. Sou Assistente Administrativo, Assistente Virtual, Programador e Analista de Dados Júnior, com habilidades de programação em Python, Flask, HTML-CSS e JavaScript. Caso precise de um dos meus serviços, me mande um e-mail por contatos. Número: +5521977080240": "Bonjour, je m'appelle Vitor Santos. Je suis Assistant Administratif, Assistant Virtuel, Programmeur et Analyste de Données Junior, avec des compétences en programmation en Python, Flask, HTML-CSS et JavaScript. Si vous avez besoin de l'un de mes services, envoyez-moi un e-mail via les contacts. Numéro : +5521977080240",

  // Section "Assistant Administratif"
  "Assistente Administrativo": "Assistant Administratif",
  "Gerenciamento de tarefas administrativas...": "Gestion des tâches administratives...",
  "Tenho Excel nível intermediário.": "J'ai Excel niveau intermédiaire.",
  "Matplotlib Nível Avançado": "Matplotlib Niveau Avancé",
  "PowerPoint Nível Intermediário": "PowerPoint Niveau Intermédiaire",
  "Word Nível Intermediário": "Word Niveau Intermédiaire",

  // Section "Programmation"
  "Programação": "Programmation",
  "Sou capaz de desenvolver aplicações web e de escritórios úteis usando Python.": "Je suis capable de développer des applications web et de bureau utiles en utilisant Python.",
  "Sou capaz de desenvolver scripts úteis para website voltados para frond-end e node para usar como servidor local.": "Je suis capable de développer des scripts utiles pour des sites web orientés front-end et node pour les utiliser comme serveur local.",
  "Sou capaz de desenvolver sites úteis para web, sites estáticos e de exibição.": "Je suis capable de développer des sites web utiles, des sites statiques et d'exposition.",
  "Faço sites responsivos e profissionais usando bootstrap.": "Je crée des sites réactifs et professionnels en utilisant bootstrap.",
  "Uso Netlify para testar sites html-ccs, bootstrap, sites com ou sem scripts do javascript, ou até mesmo para trabalho.": "J'utilise Netlify pour tester des sites html-css, bootstrap, des sites avec ou sans scripts javascript, ou même pour le travail.",
  "Uso Heroku para testar aplicações Python-Flask, ou até mesmo para trabalho usando aplicações úteis.": "J'utilise Heroku pour tester des applications Python-Flask, ou même pour le travail en utilisant des applications utiles.",

  // Section "Marketing Digital"
  "Marketing Digital": "Marketing Digital",
  "Campanhas digitais e otimização SEO... Google Search console, Site maps, Instagran, Facebook": "Campagnes digitales et optimisation SEO... Google Search Console, Site maps, Instagram, Facebook",
  "- Search Engine Optimization (SEO) - Em PT: Otimização para motores de busca": "- Search Engine Optimization (SEO) - En FR : Optimisation pour les moteurs de recherche",
  "Google Analytics - Análise de tráfego de sites...": "Google Analytics - Analyse du trafic des sites...",

  // Section "Analyste de Données"
  "Analista de dados junior": "Analyste de données junior",
  "PYTHON e FLASK para analisar dados de maneira eficiente e com perfeição, também coletar e limpar dados com precisão. usando bibliotecas que facilitam o processo em 100%": "PYTHON et FLASK pour analyser les données de manière efficace et parfaite, également collecter et nettoyer les données avec précision. En utilisant des bibliothèques qui facilitent le processus à 100%",
  "Para manipular dados e usá-los em consultas complexas de dados.": "Pour manipuler les données et les utiliser dans des requêtes complexes de données.",
  "Para armazenar dados de maneira simples e organizada.": "Pour stocker les données de manière simple et organisée.",
  "Biblioteca Chart e Leaflet, para demonstração gráfica de dados.": "Bibliothèque Chart et Leaflet, pour la démonstration graphique des données.",

  // Section "Expériences"
  "Experiências": "Expériences",
  "Outlier - geração de áudio para I.A Português para Inglês": "Outlier - génération d'audio pour I.A Portugais vers Anglais",
  "Agente de viagens - Auxiliando pessoas a conseguir passaporte com planos de cursos": "Agent de voyages - Aider les personnes à obtenir un passeport avec des plans de cours",
  "Assistente virtual - Writer translator freelancer pessoal de um amigo americano": "Assistant virtuel - Writer translator freelancer personnel d'un ami américain",
  "Auxiliar de serviços gerais - descarregando produtos de caminhão": "Auxiliaire de services généraux - Déchargement de produits de camion",
  "Ajudante de pedreiro - Ajudando a encher carrinho de areia, pegar cimentos, baldes de cimentos": "Aide-maçon - Aider à remplir la brouette de sable, prendre des ciments, des seaux de ciment",

  // Section "Capacités"
  "Capacidades PYTHON, FLASK, HTML-CSS, \"ANÁLISE DE DADOS REGRESSÃO LINEAR E TESTES\"": "Capacités PYTHON, FLASK, HTML-CSS, \"ANALYSE DE DONNÉES RÉGRESSION LINÉAIRE ET TESTS\"",
  "PROJETOS: PYTHON": "PROJETS : PYTHON",
  "Agendas comuns com banco de dados.": "Agendas communs avec base de données.",
  "Formulários com banco de dados, com hora e despertador.": "Formulaires avec base de données, avec heure et réveil.",
  "Leitor PDF com áudio.": "Lecteur PDF avec audio.",
  "Script para enviar mensagens de Email com body responsivo para mais de 20.000 pessoas \"dependendo da quantia de Emails é possível até mais\".": "Script pour envoyer des messages e-mail avec body réactif à plus de 20 000 personnes \"selon la quantité d'e-mails, il est possible d'aller encore plus loin\".",
  "Tradutor de áudio para txt, rtf ou srt.": "Traducteur d'audio en txt, rtf ou srt.",
  "Transformador de textos em áudios speach voz humana ou robótica, ou semelhante a humana.": "Transformateur de textes en audios speach voix humaine ou robotique, ou similaire à humaine.",
  "Árvore de decisão e regressão linear.": "Arbre de décision et régression linéaire.",
  "Machine Learning.": "Machine Learning.",
  "Machine Learning com estatística e probabilidade.": "Machine Learning avec statistique et probabilité.",
  "Regressão linear.": "Régression linéaire.",
  "SRT para áudio em qualquer idioma.": "SRT pour audio en n'importe quelle langue.",
  "Cortar bordas de vídeos.": "Couper les bordures des vidéos.",
  "Transformar texto em PDF.": "Transformer le texte en PDF.",
  "Transformar texto UTF-8 em texto cp1235.": "Transformer le texte UTF-8 en texte cp1235.",
  "Formulários com banco de dados, com hora e despertador.": "Formulaires avec base de données, avec heure et réveil.",
  "Planilhas de Despesas.": "Feuilles de dépenses.",
  "Dashboard gráficos.": "Tableaux de bord graphiques.",
  "Dashboard semidinâmico.": "Tableau de bord semi-dynamique.",
  "Relógios.": "Horloges.",
  "Calculadora.": "Calculatrice.",
  "App semelhante ao Wordpad.": "App similaire à Wordpad.",
  "App de edição de vídeos.": "App d'édition de vidéos.",
  "PROJETOS: FLASK": "PROJETS : FLASK",
  "Formulários com banco de dados.": "Formulaires avec base de données.",
  "Aplicação de Chat com banco de dados, possível enviar fotos e vídeos.": "Application de Chat avec base de données, possible d'envoyer des photos et des vidéos.",
  "Aplicação escreva a sua história, foto história, salvasse com banco de dados.": "Application écrivez votre histoire, photo histoire, sauvegarder avec base de données.",
  "Dashboard leitor de planilhas Excel.": "Tableau de bord lecteur de feuilles Excel.",
  "Dashboard informador de dados de planilhas excel e csv.": "Tableau de bord informateur de données de feuilles Excel et csv.",
  "Login com banco de dados.": "Login avec base de données.",
  "Formulário Dashboard online com Dash.": "Formulaire Tableau de bord en ligne avec Dash.",
  "Informação de Dados.": "Information de Données.",
  "PROJETOS: HTML-CSS": "PROJETS : HTML-CSS",
  "BOOTSTRAP": "BOOTSTRAP",
  "JAVASCRIPT": "JAVASCRIPT",
  "Site de curso para 25 idiomas diferentes.": "Site de cours pour 25 langues différentes.",
  "Lojas de roupa.": "Boutiques de vêtements.",
  "Loja de artigos religiosos.": "Boutique d'articles religieux.",
  "Formulário Pessoal.": "Formulaire Personnel.",
  "Site de conteúdo adulto.": "Site de contenu adulte.",
  "Site de jogos.": "Site de jeux.",
  "Portifólio pessoal com login e senha.": "Portfolio personnel avec login et mot de passe.",
  "Site para Clínica.": "Site pour Clinique.",
  "Site para Oficina.": "Site pour Atelier.",
  "Planilha de cálculo de despesas.": "Feuille de calcul des dépenses.",
  "Relatório de dados exemplo.": "Rapport de données exemple.",
  "ANÁLISE DE DADOS \"REGRESSÃO LINEAR E TESTES\"": "ANALYSE DE DONNÉES \"RÉGRESSION LINÉAIRE ET TESTS\"",
  "ANÁLISES FEITAS COM PYTHON, MYSQL E EXCEL": "ANALYSES FAITES AVEC PYTHON, MYSQL ET EXCEL",
  "EXIBIÇÃO DE RELATÓRIOS GRÁFICOS FLASK": "AFFICHAGE DE RAPPORTS GRAPHIQUES FLASK",
  ", BOOTSTRAP, JAVASCRIPT": ", BOOTSTRAP, JAVASCRIPT",
  "CONHECIMENTOS E CAPACIDADES ABAIXO": "CONNAISSANCES ET CAPACITÉS CI-DESSOUS",
  "Experiência com Modelagem Estatística.": "Expérience avec Modélisation Statistique.",
  "statsmodels e scikit-learn.": "statsmodels et scikit-learn.",
  "Gestão e Manipulação de Bancos de Dados MYSQL.": "Gestion et Manipulation de Bases de Données MYSQL.",
  "Realização de análise estatística básica Excel.": "Réalisation d'analyse statistique de base Excel.",
  "Criação de dashboards interativos e relatórios dinâmicos Matplotlib, Chart e Leaflet.": "Création de tableaux de bord interactifs et rapports dynamiques Matplotlib, Chart et Leaflet.",

  // Section "Contact"
  "Contato": "Contact",
  "Entre em contato comigo por email.": "Contactez-moi par e-mail.",
  "Nome:": "Nom :",
  "Email:": "E-mail :",
  "Mensagem:": "Message :",
  "Enviar mensagem": "Envoyer un message",
  "Ou converse comigo através do WhatsApp.": "Ou discutez avec moi via WhatsApp."
},
        ru: {
  // Раздел "Обо мне"
  "Sobre mim": "Обо мне",
           "SOBRE MIM": "Обо Мне",
    "PROGRAMAÇÃO": "Программирование",
    "ASSISTENTE ADMINISTRATIVO": "Административный Помощник",
    "MARKETING DIGITAL": "Цифровой Маркетинг",
    "ANALISTA DE DADOS": "Аналитик Данных",
    "EXPERIÊNCIAS": "Опыт",
    "CAPACIDADES": "Навыки",
    "CONTATO": "Контакт",
  "Olá, me chamo Vitor Santos. Sou Assistente Administrativo, Assistente Virtual, Programador e Analista de Dados Júnior, com habilidades de programação em Python, Flask, HTML-CSS e JavaScript. Caso precise de um dos meus serviços, me mande um e-mail por contatos. Número: +5521977080240": "Здравствуйте, меня зовут Витор Сантос. Я административный ассистент, виртуальный ассистент, программист и младший аналитик данных с навыками программирования на Python, Flask, HTML-CSS и JavaScript. Если вам нужны мои услуги, отправьте мне электронное письмо через контакты. Номер: +5521977080240",

  // Раздел "Административный ассистент"
  "Assistente Administrativo": "Административный ассистент",
  "Gerenciamento de tarefas administrativas...": "Управление административными задачами...",
  "Tenho Excel nível intermediário.": "У меня средний уровень Excel.",
  "Matplotlib Nível Avançado": "Matplotlib Продвинутый уровень",
  "PowerPoint Nível Intermediário": "PowerPoint Средний уровень",
  "Word Nível Intermediário": "Word Средний уровень",

  // Раздел "Программирование"
  "Programação": "Программирование",
  "Sou capaz de desenvolver aplicações web e de escritórios úteis usando Python.": "Я могу разрабатывать полезные веб-приложения и офисные приложения с использованием Python.",
  "Sou capaz de desenvolver scripts úteis para website voltados para frond-end e node para usar como servidor local.": "Я могу разрабатывать полезные скрипты для веб-сайтов, ориентированных на front-end и node, для использования в качестве локального сервера.",
  "Sou capaz de desenvolver sites úteis para web, sites estáticos e de exibição.": "Я могу разрабатывать полезные веб-сайты, статические сайты и сайты для демонстрации.",
  "Faço sites responsivos e profissionais usando bootstrap.": "Я создаю адаптивные и профессиональные сайты с использованием bootstrap.",
  "Uso Netlify para testar sites html-ccs, bootstrap, sites com ou sem scripts do javascript, ou até mesmo para trabalho.": "Я использую Netlify для тестирования сайтов html-css, bootstrap, сайтов с или без скриптов javascript, или даже для работы.",
  "Uso Heroku para testar aplicações Python-Flask, ou até mesmo para trabalho usando aplicações úteis.": "Я использую Heroku для тестирования приложений Python-Flask или даже для работы с использованием полезных приложений.",

  // Раздел "Цифровой маркетинг"
  "Marketing Digital": "Цифровой маркетинг",
  "Campanhas digitais e otimização SEO... Google Search console, Site maps, Instagran, Facebook": "Цифровые кампании и оптимизация SEO... Google Search Console, Site maps, Instagram, Facebook",
  "- Search Engine Optimization (SEO) - Em PT: Otimização para motores de busca": "- Search Engine Optimization (SEO) - На русском: Оптимизация для поисковых систем",
  "Google Analytics - Análise de tráfego de sites...": "Google Analytics - Анализ трафика сайтов...",

  // Раздел "Аналитик данных"
  "Analista de dados junior": "Младший аналитик данных",
  "PYTHON e FLASK para analisar dados de maneira eficiente e com perfeição, também coletar e limpar dados com precisão. usando bibliotecas que facilitam o processo em 100%": "PYTHON и FLASK для эффективного и идеального анализа данных, а также для сбора и очистки данных с точностью. Использую библиотеки, которые облегчают процесс на 100%",
  "Para manipular dados e usá-los em consultas complexas de dados.": "Для манипуляции данными и их использования в сложных запросах данных.",
  "Para armazenar dados de maneira simples e organizada.": "Для хранения данных простым и организованным способом.",
  "Biblioteca Chart e Leaflet, para demonstração gráfica de dados.": "Библиотека Chart и Leaflet для графической демонстрации данных.",

  // Раздел "Опыт"
  "Experiências": "Опыт",
  "Outlier - geração de áudio para I.A Português para Inglês": "Outlier - генерация аудио для ИИ с португальского на английский",
  "Agente de viagens - Auxiliando pessoas a conseguir passaporte com planos de cursos": "Агент по путешествиям - Помощь людям в получении паспорта с планами курсов",
  "Assistente virtual - Writer translator freelancer pessoal de um amigo americano": "Виртуальный ассистент - Писатель, переводчик, фрилансер, личный помощник американского друга",
  "Auxiliar de serviços gerais - descarregando produtos de caminhão": "Помощник по общим услугам - Разгрузка продуктов с грузовика",
  "Ajudante de pedreiro - Ajudando a encher carrinho de areia, pegar cimentos, baldes de cimentos": "Помощник каменщика - Помощь в наполнении тачки песком, взятии цемента, ведер с цементом",

  // Раздел "Навыки"
  "Capacidades PYTHON, FLASK, HTML-CSS, \"ANÁLISE DE DADOS REGRESSÃO LINEAR E TESTES\"": "Навыки PYTHON, FLASK, HTML-CSS, \"АНАЛИЗ ДАННЫХ ЛИНЕЙНАЯ РЕГРЕССИЯ И ТЕСТЫ\"",
  "PROJETOS: PYTHON": "ПРОЕКТЫ: PYTHON",
  "Agendas comuns com banco de dados.": "Обычные расписания с базой данных.",
  "Formulários com banco de dados, com hora e despertador.": "Формы с базой данных, с временем и будильником.",
  "Leitor PDF com áudio.": "PDF-ридер с аудио.",
  "Script para enviar mensagens de Email com body responsivo para mais de 20.000 pessoas \"dependendo da quantia de Emails é possível até mais\".": "Скрипт для отправки электронных писем с адаптивным телом для более чем 20 000 человек \"в зависимости от количества писем возможно даже больше\".",
  "Tradutor de áudio para txt, rtf ou srt.": "Переводчик аудио в txt, rtf или srt.",
  "Transformador de textos em áudios speach voz humana ou robótica, ou semelhante a humana.": "Преобразователь текстов в аудио speach человеческим или роботизированным голосом, или похожим на человеческий.",
  "Árvore de decisão e regressão linear.": "Дерево решений и линейная регрессия.",
  "Machine Learning.": "Машинное обучение.",
  "Machine Learning com estatística e probabilidade.": "Машинное обучение со статистикой и вероятностью.",
  "Regressão linear.": "Линейная регрессия.",
  "SRT para áudio em qualquer idioma.": "SRT для аудио на любом языке.",
  "Cortar bordas de vídeos.": "Обрезка краев видео.",
  "Transformar texto em PDF.": "Преобразование текста в PDF.",
  "Transformar texto UTF-8 em texto cp1235.": "Преобразование текста UTF-8 в текст cp1235.",
  "Formulários com banco de dados, com hora e despertador.": "Формы с базой данных, с временем и будильником.",
  "Planilhas de Despesas.": "Таблицы расходов.",
  "Dashboard gráficos.": "Графические панели.",
  "Dashboard semidinâmico.": "Полудинамическая панель.",
  "Relógios.": "Часы.",
  "Calculadora.": "Калькулятор.",
  "App semelhante ao Wordpad.": "Приложение, похожее на Wordpad.",
  "App de edição de vídeos.": "Приложение для редактирования видео.",
  "PROJETOS: FLASK": "ПРОЕКТЫ: FLASK",
  "Formulários com banco de dados.": "Формы с базой данных.",
  "Aplicação de Chat com banco de dados, possível enviar fotos e vídeos.": "Чат-приложение с базой данных, возможность отправки фото и видео.",
  "Aplicação escreva a sua história, foto história, salvasse com banco de dados.": "Приложение \"Напишите свою историю\", фото истории, сохранение с базой данных.",
  "Dashboard leitor de planilhas Excel.": "Панель для чтения таблиц Excel.",
  "Dashboard informador de dados de planilhas excel e csv.": "Панель для информирования данных из таблиц Excel и csv.",
  "Login com banco de dados.": "Логин с базой данных.",
  "Formulário Dashboard online com Dash.": "Онлайн-форма панели с Dash.",
  "Informação de Dados.": "Информация о данных.",
  "PROJETOS: HTML-CSS": "ПРОЕКТЫ: HTML-CSS",
  "BOOTSTRAP": "BOOTSTRAP",
  "JAVASCRIPT": "JAVASCRIPT",
  "Site de curso para 25 idiomas diferentes.": "Сайт курсов для 25 разных языков.",
  "Lojas de roupa.": "Магазины одежды.",
  "Loja de artigos religiosos.": "Магазин религиозных товаров.",
  "Formulário Pessoal.": "Личная форма.",
  "Site de conteúdo adulto.": "Сайт для взрослых.",
  "Site de jogos.": "Сайт игр.",
  "Portifólio pessoal com login e senha.": "Личное портфолио с логином и паролем.",
  "Site para Clínica.": "Сайт для клиники.",
  "Site para Oficina.": "Сайт для мастерской.",
  "Planilha de cálculo de despesas.": "Таблица расчета расходов.",
  "Relatório de dados exemplo.": "Пример отчета данных.",
  "ANÁLISE DE DADOS \"REGRESSÃO LINEAR E TESTES\"": "АНАЛИЗ ДАННЫХ \"ЛИНЕЙНАЯ РЕГРЕССИЯ И ТЕСТЫ\"",
  "ANÁLISES FEITAS COM PYTHON, MYSQL E EXCEL": "АНАЛИЗЫ, ВЫПОЛНЕННЫЕ С PYTHON, MYSQL И EXCEL",
  "EXIBIÇÃO DE RELATÓRIOS GRÁFICOS FLASK": "ОТОБРАЖЕНИЕ ГРАФИЧЕСКИХ ОТЧЕТОВ FLASK",
  ", BOOTSTRAP, JAVASCRIPT": ", BOOTSTRAP, JAVASCRIPT",
  "CONHECIMENTOS E CAPACIDADES ABAIXO": "ЗНАНИЯ И НАВЫКИ НИЖЕ",
  "Experiência com Modelagem Estatística.": "Опыт статистического моделирования.",
  "statsmodels e scikit-learn.": "statsmodels и scikit-learn.",
  "Gestão e Manipulação de Bancos de Dados MYSQL.": "Управление и манипуляция базами данных MYSQL.",
  "Realização de análise estatística básica Excel.": "Выполнение базового статистического анализа Excel.",
  "Criação de dashboards interativos e relatórios dinâmicos Matplotlib, Chart e Leaflet.": "Создание интерактивных панелей и динамических отчетов Matplotlib, Chart и Leaflet.",

  // Раздел "Контакт"
  "Contato": "Контакт",
  "Entre em contato comigo por email.": "Свяжитесь со мной по электронной почте.",
  "Nome:": "Имя:",
  "Email:": "Электронная почта:",
  "Mensagem:": "Сообщение:",
  "Enviar mensagem": "Отправить сообщение",
  "Ou converse comigo através do WhatsApp.": "Или свяжитесь со мной через WhatsApp."
},
        zh: {
  // 部分 "关于我"
  "Sobre mim": "关于我",
             "SOBRE MIM": "关于我",
    "PROGRAMAÇÃO": "编程",
    "ASSISTENTE ADMINISTRATIVO": "行政助理",
    "MARKETING DIGITAL": "数字营销",
    "ANALISTA DE DADOS": "数据分析师",
    "EXPERIÊNCIAS": "经验",
    "CAPACIDADES": "能力",
    "CONTATO": "联系",
  "Olá, me chamo Vitor Santos. Sou Assistente Administrativo, Assistente Virtual, Programador e Analista de Dados Júnior, com habilidades de programação em Python, Flask, HTML-CSS e JavaScript. Caso precise de um dos meus serviços, me mande um e-mail por contatos. Número: +5521977080240": "你好，我叫Vitor Santos。我是行政助理、虚拟助理、程序员和初级数据分析师，具备Python、Flask、HTML-CSS和JavaScript编程技能。如果您需要我的服务，请通过联系人发送电子邮件给我。号码：+5521977080240",

  // 部分 "行政助理"
  "Assistente Administrativo": "行政助理",
  "Gerenciamento de tarefas administrativas...": "管理行政任务...",
  "Tenho Excel nível intermediário.": "我具备中级Excel水平。",
  "Matplotlib Nível Avançado": "Matplotlib 高级水平",
  "PowerPoint Nível Intermediário": "PowerPoint 中级水平",
  "Word Nível Intermediário": "Word 中级水平",

  // 部分 "编程"
  "Programação": "编程",
  "Sou capaz de desenvolver aplicações web e de escritórios úteis usando Python.": "我能够使用Python开发有用的Web应用程序和办公应用程序。",
  "Sou capaz de desenvolver scripts úteis para website voltados para frond-end e node para usar como servidor local.": "我能够开发用于前端和Node的有用脚本，用作本地服务器。",
  "Sou capaz de desenvolver sites úteis para web, sites estáticos e de exibição.": "我能够开发有用的网站、静态网站和展示网站。",
  "Faço sites responsivos e profissionais usando bootstrap.": "我使用Bootstrap制作响应式和专业的网站。",
  "Uso Netlify para testar sites html-ccs, bootstrap, sites com ou sem scripts do javascript, ou até mesmo para trabalho.": "我使用Netlify测试HTML-CSS、Bootstrap网站，无论是否包含JavaScript脚本，甚至用于工作。",
  "Uso Heroku para testar aplicações Python-Flask, ou até mesmo para trabalho usando aplicações úteis.": "我使用Heroku测试Python-Flask应用程序，甚至用于工作使用有用的应用程序。",

  // 部分 "数字营销"
  "Marketing Digital": "数字营销",
  "Campanhas digitais e otimização SEO... Google Search console, Site maps, Instagran, Facebook": "数字营销活动和SEO优化... Google Search Console、网站地图、Instagram、Facebook",
  "- Search Engine Optimization (SEO) - Em PT: Otimização para motores de busca": "- 搜索引擎优化 (SEO) - 中文：搜索引擎优化",
  "Google Analytics - Análise de tráfego de sites...": "Google Analytics - 网站流量分析...",

  // 部分 "数据分析师"
  "Analista de dados junior": "初级数据分析师",
  "PYTHON e FLASK para analisar dados de maneira eficiente e com perfeição, também coletar e limpar dados com precisão. usando bibliotecas que facilitam o processo em 100%": "使用PYTHON和FLASK高效且完美地分析数据，并精确收集和清理数据。使用使过程简化100%的库。",
  "Para manipular dados e usá-los em consultas complexas de dados.": "用于操作数据并将其用于复杂的数据查询。",
  "Para armazenar dados de maneira simples e organizada.": "用于以简单和有序的方式存储数据。",
  "Biblioteca Chart e Leaflet, para demonstração gráfica de dados.": "Chart和Leaflet库，用于数据的图形展示。",

  // 部分 "经验"
  "Experiências": "经验",
  "Outlier - geração de áudio para I.A Português para Inglês": "Outlier - 为AI生成葡萄牙语到英语的音频",
  "Agente de viagens - Auxiliando pessoas a conseguir passaporte com planos de cursos": "旅行代理 - 帮助人们通过课程计划获得护照",
  "Assistente virtual - Writer translator freelancer pessoal de um amigo americano": "虚拟助理 - 为一位美国朋友的个人作家和翻译自由职业者",
  "Auxiliar de serviços gerais - descarregando produtos de caminhão": "一般服务助理 - 卸货卡车产品",
  "Ajudante de pedreiro - Ajudando a encher carrinho de areia, pegar cimentos, baldes de cimentos": "泥瓦匠助手 - 帮助装满沙车、拿水泥、水泥桶",

  // 部分 "能力"
  "Capacidades PYTHON, FLASK, HTML-CSS, \"ANÁLISE DE DADOS REGRESSÃO LINEAR E TESTES\"": "能力 PYTHON, FLASK, HTML-CSS, \"数据分析 线性回归和测试\"",
  "PROJETOS: PYTHON": "项目: PYTHON",
  "Agendas comuns com banco de dados.": "带数据库的普通日程表。",
  "Formulários com banco de dados, com hora e despertador.": "带数据库的表单，带时间和闹钟。",
  "Leitor PDF com áudio.": "带音频的PDF阅读器。",
  "Script para enviar mensagens de Email com body responsivo para mais de 20.000 pessoas \"dependendo da quantia de Emails é possível até mais\".": "用于发送带响应式正文的电子邮件的脚本，适用于超过20,000人 \"根据电子邮件数量，甚至可以更多\"。",
  "Tradutor de áudio para txt, rtf ou srt.": "将音频翻译为txt、rtf或srt。",
  "Transformador de textos em áudios speach voz humana ou robótica, ou semelhante a humana.": "将文本转换为人类语音或机器人语音的音频，或类似人类语音。",
  "Árvore de decisão e regressão linear.": "决策树和线性回归。",
  "Machine Learning.": "机器学习。",
  "Machine Learning com estatística e probabilidade.": "带统计和概率的机器学习。",
  "Regressão linear.": "线性回归。",
  "SRT para áudio em qualquer idioma.": "将SRT转换为任何语言的音频。",
  "Cortar bordas de vídeos.": "裁剪视频边缘。",
  "Transformar texto em PDF.": "将文本转换为PDF。",
  "Transformar texto UTF-8 em texto cp1235.": "将UTF-8文本转换为cp1235文本。",
  "Formulários com banco de dados, com hora e despertador.": "带数据库的表单，带时间和闹钟。",
  "Planilhas de Despesas.": "支出表。",
  "Dashboard gráficos.": "图形仪表板。",
  "Dashboard semidinâmico.": "半动态仪表板。",
  "Relógios.": "时钟。",
  "Calculadora.": "计算器。",
  "App semelhante ao Wordpad.": "类似于Wordpad的应用程序。",
  "App de edição de vídeos.": "视频编辑应用程序。",
  "PROJETOS: FLASK": "项目: FLASK",
  "Formulários com banco de dados.": "带数据库的表单。",
  "Aplicação de Chat com banco de dados, possível enviar fotos e vídeos.": "带数据库的聊天应用程序，可以发送照片和视频。",
  "Aplicação escreva a sua história, foto história, salvasse com banco de dados.": "写下你的故事的应用程序，照片故事，保存到数据库。",
  "Dashboard leitor de planilhas Excel.": "Excel表格阅读器仪表板。",
  "Dashboard informador de dados de planilhas excel e csv.": "Excel和CSV数据信息仪表板。",
  "Login com banco de dados.": "带数据库的登录。",
  "Formulário Dashboard online com Dash.": "带Dash的在线仪表板表单。",
  "Informação de Dados.": "数据信息。",
  "PROJETOS: HTML-CSS": "项目: HTML-CSS",
  "BOOTSTRAP": "BOOTSTRAP",
  "JAVASCRIPT": "JAVASCRIPT",
  "Site de curso para 25 idiomas diferentes.": "25种不同语言的课程网站。",
  "Lojas de roupa.": "服装店。",
  "Loja de artigos religiosos.": "宗教用品店。",
  "Formulário Pessoal.": "个人表单。",
  "Site de conteúdo adulto.": "成人内容网站。",
  "Site de jogos.": "游戏网站。",
  "Portifólio pessoal com login e senha.": "带登录和密码的个人作品集。",
  "Site para Clínica.": "诊所网站。",
  "Site para Oficina.": "工作室网站。",
  "Planilha de cálculo de despesas.": "支出计算表。",
  "Relatório de dados exemplo.": "数据报告示例。",
  "ANÁLISE DE DADOS \"REGRESSÃO LINEAR E TESTES\"": "数据分析 \"线性回归和测试\"",
  "ANÁLISES FEITAS COM PYTHON, MYSQL E EXCEL": "使用PYTHON、MYSQL和EXCEL进行的分析",
  "EXIBIÇÃO DE RELATÓRIOS GRÁFICOS FLASK": "FLASK图形报告展示",
  ", BOOTSTRAP, JAVASCRIPT": ", BOOTSTRAP, JAVASCRIPT",
  "CONHECIMENTOS E CAPACIDADES ABAIXO": "以下知识和能力",
  "Experiência com Modelagem Estatística.": "统计建模经验。",
  "statsmodels e scikit-learn.": "statsmodels和scikit-learn。",
  "Gestão e Manipulação de Bancos de Dados MYSQL.": "MYSQL数据库管理和操作。",
  "Realização de análise estatística básica Excel.": "执行基本的Excel统计分析。",
  "Criação de dashboards interativos e relatórios dinâmicos Matplotlib, Chart e Leaflet.": "创建交互式仪表板和动态报告Matplotlib、Chart和Leaflet。",

  // 部分 "联系"
  "Contato": "联系",
  "Entre em contato comigo por email.": "通过电子邮件与我联系。",
  "Nome:": "姓名：",
  "Email:": "电子邮件：",
  "Mensagem:": "消息：",
  "Enviar mensagem": "发送消息",
  "Ou converse comigo através do WhatsApp.": "或通过WhatsApp与我联系。"
},
        ja: {
  // セクション「私について」
  "Sobre mim": "私について",
       "SOBRE MIM": "私について",
    "PROGRAMAÇÃO": "プログラミング",
    "ASSISTENTE ADMINISTRATIVO": "管理アシスタント",
    "MARKETING DIGITAL": "デジタルマーケティング",
    "ANALISTA DE DADOS": "データアナリスト",
    "EXPERIÊNCIAS": "経験",
    "CAPACIDADES": "能力",
    "CONTATO": "連絡先",
  "Olá, me chamo Vitor Santos. Sou Assistente Administrativo, Assistente Virtual, Programador e Analista de Dados Júnior, com habilidades de programação em Python, Flask, HTML-CSS e JavaScript. Caso precise de um dos meus serviços, me mande um e-mail por contatos. Número: +5521977080240": "こんにちは、私はVitor Santosと申します。行政アシスタント、バーチャルアシスタント、プログラマー、ジュニアデータアナリストとして、Python、Flask、HTML-CSS、JavaScriptのプログラミングスキルを持っています。私のサービスが必要な場合は、連絡先からメールを送ってください。電話番号：+5521977080240",

  // セクション「行政アシスタント」
  "Assistente Administrativo": "行政アシスタント",
  "Gerenciamento de tarefas administrativas...": "管理タスクの処理...",
  "Tenho Excel nível intermediário.": "私は中級レベルのExcelスキルを持っています。",
  "Matplotlib Nível Avançado": "Matplotlib 上級レベル",
  "PowerPoint Nível Intermediário": "PowerPoint 中級レベル",
  "Word Nível Intermediário": "Word 中級レベル",

  // セクション「プログラミング」
  "Programação": "プログラミング",
  "Sou capaz de desenvolver aplicações web e de escritórios úteis usando Python.": "Pythonを使用して、便利なWebアプリケーションやオフィスアプリケーションを開発できます。",
  "Sou capaz de desenvolver scripts úteis para website voltados para frond-end e node para usar como servidor local.": "フロントエンドやNode向けの便利なスクリプトを開発し、ローカルサーバーとして使用できます。",
  "Sou capaz de desenvolver sites úteis para web, sites estáticos e de exibição.": "便利なWebサイト、静的サイト、展示用サイトを開発できます。",
  "Faço sites responsivos e profissionais usando bootstrap.": "Bootstrapを使用して、レスポンシブでプロフェッショナルなサイトを作成します。",
  "Uso Netlify para testar sites html-ccs, bootstrap, sites com ou sem scripts do javascript, ou até mesmo para trabalho.": "Netlifyを使用して、HTML-CSS、Bootstrapのサイトをテストします。JavaScriptのスクリプトの有無にかかわらず、仕事にも使用します。",
  "Uso Heroku para testar aplicações Python-Flask, ou até mesmo para trabalho usando aplicações úteis.": "Herokuを使用して、Python-Flaskアプリケーションをテストします。便利なアプリケーションを使用して仕事にも活用します。",

  // セクション「デジタルマーケティング」
  "Marketing Digital": "デジタルマーケティング",
  "Campanhas digitais e otimização SEO... Google Search console, Site maps, Instagran, Facebook": "デジタルキャンペーンとSEO最適化... Google Search Console、サイトマップ、Instagram、Facebook",
  "- Search Engine Optimization (SEO) - Em PT: Otimização para motores de busca": "- 検索エンジン最適化 (SEO) - 日本語：検索エンジン最適化",
  "Google Analytics - Análise de tráfego de sites...": "Google Analytics - サイトトラフィック分析...",

  // セクション「データアナリスト」
  "Analista de dados junior": "ジュニアデータアナリスト",
  "PYTHON e FLASK para analisar dados de maneira eficiente e com perfeição, também coletar e limpar dados com precisão. usando bibliotecas que facilitam o processo em 100%": "PYTHONとFLASKを使用して、効率的かつ完璧にデータを分析し、正確にデータを収集およびクリーニングします。プロセスを100％簡素化するライブラリを使用します。",
  "Para manipular dados e usá-los em consultas complexas de dados.": "データを操作し、複雑なデータクエリに使用します。",
  "Para armazenar dados de maneira simples e organizada.": "データをシンプルかつ整理された方法で保存します。",
  "Biblioteca Chart e Leaflet, para demonstração gráfica de dados.": "ChartとLeafletライブラリを使用して、データをグラフィカルに表示します。",

  // セクション「経験」
  "Experiências": "経験",
  "Outlier - geração de áudio para I.A Português para Inglês": "Outlier - AI向けのポルトガル語から英語への音声生成",
  "Agente de viagens - Auxiliando pessoas a conseguir passaporte com planos de cursos": "旅行代理店 - コースプランを通じてパスポート取得を支援",
  "Assistente virtual - Writer translator freelancer pessoal de um amigo americano": "バーチャルアシスタント - アメリカ人友人の個人ライター兼翻訳フリーランサー",
  "Auxiliar de serviços gerais - descarregando produtos de caminhão": "一般サービスアシスタント - トラックからの商品の荷降ろし",
  "Ajudante de pedreiro - Ajudando a encher carrinho de areia, pegar cimentos, baldes de cimentos": "左官助手 - 砂を手押し車に詰めるのを手伝い、セメントやセメントのバケツを運ぶ",

  // セクション「能力」
  "Capacidades PYTHON, FLASK, HTML-CSS, \"ANÁLISE DE DADOS REGRESSÃO LINEAR E TESTES\"": "能力 PYTHON, FLASK, HTML-CSS, \"データ分析 線形回帰とテスト\"",
  "PROJETOS: PYTHON": "プロジェクト: PYTHON",
  "Agendas comuns com banco de dados.": "データベース付きの一般的なスケジュール。",
  "Formulários com banco de dados, com hora e despertador.": "データベース付きのフォーム、時間とアラーム付き。",
  "Leitor PDF com áudio.": "音声付きPDFリーダー。",
  "Script para enviar mensagens de Email com body responsivo para mais de 20.000 pessoas \"dependendo da quantia de Emails é possível até mais\".": "20,000人以上にレスポンシブな本文のメールを送信するスクリプト \"メールの量によってはさらに可能\"。",
  "Tradutor de áudio para txt, rtf ou srt.": "音声をtxt、rtf、またはsrtに翻訳。",
  "Transformador de textos em áudios speach voz humana ou robótica, ou semelhante a humana.": "テキストを人間の声やロボット声の音声に変換、または人間に似た声に変換。",
  "Árvore de decisão e regressão linear.": "決定木と線形回帰。",
  "Machine Learning.": "機械学習。",
  "Machine Learning com estatística e probabilidade.": "統計と確率を用いた機械学習。",
  "Regressão linear.": "線形回帰。",
  "SRT para áudio em qualquer idioma.": "SRTを任意の言語の音声に変換。",
  "Cortar bordas de vídeos.": "動画の端を切り取る。",
  "Transformar texto em PDF.": "テキストをPDFに変換。",
  "Transformar texto UTF-8 em texto cp1235.": "UTF-8テキストをcp1235テキストに変換。",
  "Formulários com banco de dados, com hora e despertador.": "データベース付きのフォーム、時間とアラーム付き。",
  "Planilhas de Despesas.": "支出表。",
  "Dashboard gráficos.": "グラフィカルダッシュボード。",
  "Dashboard semidinâmico.": "セミダイナミックダッシュボード。",
  "Relógios.": "時計。",
  "Calculadora.": "計算機。",
  "App semelhante ao Wordpad.": "Wordpadに似たアプリ。",
  "App de edição de vídeos.": "動画編集アプリ。",
  "PROJETOS: FLASK": "プロジェクト: FLASK",
  "Formulários com banco de dados.": "データベース付きのフォーム。",
  "Aplicação de Chat com banco de dados, possível enviar fotos e vídeos.": "データベース付きチャットアプリケーション、写真や動画を送信可能。",
  "Aplicação escreva a sua história, foto história, salvasse com banco de dados.": "あなたの物語を書くアプリケーション、写真物語、データベースに保存。",
  "Dashboard leitor de planilhas Excel.": "Excelシートリーダーダッシュボード。",
  "Dashboard informador de dados de planilhas excel e csv.": "ExcelおよびCSVデータインフォーマーダッシュボード。",
  "Login com banco de dados.": "データベース付きログイン。",
  "Formulário Dashboard online com Dash.": "Dashを使用したオンラインダッシュボードフォーム。",
  "Informação de Dados.": "データ情報。",
  "PROJETOS: HTML-CSS": "プロジェクト: HTML-CSS",
  "BOOTSTRAP": "BOOTSTRAP",
  "JAVASCRIPT": "JAVASCRIPT",
  "Site de curso para 25 idiomas diferentes.": "25の異なる言語のコースサイト。",
  "Lojas de roupa.": "衣料品店。",
  "Loja de artigos religiosos.": "宗教用品店。",
  "Formulário Pessoal.": "個人フォーム。",
  "Site de conteúdo adulto.": "アダルトコンテンツサイト。",
  "Site de jogos.": "ゲームサイト。",
  "Portifólio pessoal com login e senha.": "ログインとパスワード付きの個人ポートフォリオ。",
  "Site para Clínica.": "クリニック向けサイト。",
  "Site para Oficina.": "ワークショップ向けサイト。",
  "Planilha de cálculo de despesas.": "支出計算シート。",
  "Relatório de dados exemplo.": "データレポート例。",
  "ANÁLISE DE DADOS \"REGRESSÃO LINEAR E TESTES\"": "データ分析 \"線形回帰とテスト\"",
  "ANÁLISES FEITAS COM PYTHON, MYSQL E EXCEL": "PYTHON、MYSQL、EXCELを使用した分析",
  "EXIBIÇÃO DE RELATÓRIOS GRÁFICOS FLASK": "FLASKグラフィカルレポート表示",
  ", BOOTSTRAP, JAVASCRIPT": ", BOOTSTRAP, JAVASCRIPT",
  "CONHECIMENTOS E CAPACIDADES ABAIXO": "以下の知識と能力",
  "Experiência com Modelagem Estatística.": "統計モデリングの経験。",
  "statsmodels e scikit-learn.": "statsmodelsとscikit-learn。",
  "Gestão e Manipulação de Bancos de Dados MYSQL.": "MYSQLデータベースの管理と操作。",
  "Realização de análise estatística básica Excel.": "基本的なExcel統計分析の実行。",
  "Criação de dashboards interativos e relatórios dinâmicos Matplotlib, Chart e Leaflet.": "Matplotlib、Chart、Leafletを使用したインタラクティブなダッシュボードと動的レポートの作成。",

  // セクション「連絡先」
  "Contato": "連絡先",
  "Entre em contato comigo por email.": "メールで連絡してください。",
  "Nome:": "名前：",
  "Email:": "メール：",
  "Mensagem:": "メッセージ：",
  "Enviar mensagem": "メッセージを送る",
  "Ou converse comigo através do WhatsApp.": "またはWhatsAppで連絡してください。"
}
      };
  
const languageSelect = document.getElementById('language-select');

languageSelect.addEventListener('change', (event) => {
  const selectedLanguage = event.target.value;
  translatePage(selectedLanguage);
});

function translatePage(language) {
  const elements = document.querySelectorAll('[data-lang]');
  elements.forEach(element => {
    const key = element.getAttribute('data-lang') || element.textContent.trim();
    if (translations[language] && translations[language][key]) {
      element.textContent = translations[language][key];
    } else {
      console.warn("Tradução não encontrada para:", key);
      element.textContent = `[Tradução não disponível] ${element.textContent}`;
    }
  });
}
